# Generated by Django 4.1.2 on 2022-10-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchId', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=20)),
                ('streetNumber', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('unitNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber1', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneNumber3', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('fuelType', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=20)),
                ('licencePlate', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('mileage', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('dailyCost', models.IntegerField(default=0)),
                ('weeklyCost', models.IntegerField(default=0)),
                ('monthlyCost', models.IntegerField(default=0)),
                ('lateFee', models.IntegerField(default=0)),
                ('changeBranchFee', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('driversLicense', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('goldMember', models.BooleanField(default=False)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=20)),
                ('streetNumber', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('unitNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber1', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneNumber3', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('rank', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=20)),
                ('streetNumber', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('unitNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber1', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneNumber3', models.CharField(blank=True, max_length=15, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rentalId', models.AutoField(primary_key=True, serialize=False)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('dateReturned', models.DateField()),
                ('totalCost', models.IntegerField(default=0)),
                ('licensePlate', models.CharField(max_length=20)),
                ('goldMember', models.BooleanField(default=False)),
                ('branchArr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchA', to='api.branch')),
                ('branchDep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchD', to='api.branch')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('carType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='carType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartype'),
        ),
    ]
