# Generated by Django 4.1.2 on 2022-10-26 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cartype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='dateReturned',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
